import json
import re
from docx2python import docx2python

def process_master_scholarships(file_name):
    print("Reading file and applying Knowledge Base locations... (Final Mode)")
    
    # --- EXPANDED KNOWLEDGE BASE: SMART LOCATION MAPPING ---
    uni_map = {
        "ACU (The Association of Commonwealth Universities)": "London, United Kingdom",
        "ACES: The Society for Editing": "Indianapolis, United States",
        "Ayn Rand Institute": "Santa Ana, United States",
        "ACES Education Fund": "Indianapolis, United States",
        "Amber Scholar": "Pune, India",
        "Amber Student": "Pune, India",
        "Algonquin College": "Ottawa, Canada",
        "ADB/Japan Government": "Manila, Philippines",
        "Association of Certified Fraud Examiners (ACFE)": "Austin, United States",
        "Association of Writers & Writing Programs": "Norfolk, United States",
        "AW Bridal": "Nevada, United States",
        "Aston University": "Birmingham, United Kingdom",
        "Arctic Chiropractic Fairbanks": "Fairbanks, United States",
        "Auger & Auger Accident and Injury Lawyers": "Charlotte, United States",
        "AUFIN Education & Scholarship": "Sydney, Australia",
        "British University Vietnam": "Hung Yen, Vietnam",
        "Bio-Techne": "Minneapolis, United States",
        "Beijing Government": "Beijing, China",
        "BOCSCI Inc.": "Shirley, United States",
        "Brooklyn Injury Attorneys P.C.": "Brooklyn, United States",
        "Bronx Injury Lawyers P.C.": "Bronx, United States",
        "Boland Injury Lawyers P.C.": "Queens, United States",
        "Brian C. Jensen": "Philadelphia, United States",
        "Bournemouth University": "Bournemouth, United Kingdom",
        "Brunel University of London": "London, United Kingdom",
        "Creative BioMart": "Shirley, United States",
        "CryptoRunner": "Stockholm, Sweden",
        "CouponBirds": "Santa Monica, United States",
        "College JumpStart Scholarship": "Madison, United States",
        "Cranfield University": "Cranfield, United Kingdom",
        "Cassandra Toroian": "Philadelphia, United States",
        "Centro Legal Hispano de Las Vegas": "Las Vegas, United States",
        "CEMFI": "Madrid, Spain",
        "Charles Sturt University": "Bathurst, Australia",
        "Diamant Gerstein": "New York City, United States",
        "Delete Cyberbullying": "Los Angeles, United States",
        "Drug Rehab USA": "Deerfield Beach, United States",
        "Deakin University": "Melbourne, Australia",
        "Editor World LLC": "Newport News, United States",
        "educations.com": "Stockholm, Sweden",
        "Enkla Media - Kreditkortlistan": "Stockholm, Sweden",
        "European Commission": "Brussels, Belgium",
        "ESDES Business School": "Lyon, France",
        "Education USA": "Washington, D.C., United States",
        "Engineering Institute of Technology": "Perth, Australia",
        "Eastern Mediterranean University": "Famagusta, Cyprus",
        "FHE Health": "Deerfield Beach, United States",
        "Florida Rentals": "Florida, United States",
        "For a Bright Future Foundation": "Florida, United States",
        "Farmer & Morris Law, PLLC": "Rutherfordton, United States",
        "Global Sustainable Electricity Partnership": "Montreal, Canada",
        "Government Of Canada": "Ottawa, Canada",
        "Government of Flanders": "Brussels, Belgium",
        "GBSB Global Business School": "Barcelona, Spain",
        "Green Light Booking": "Pleasant Grove, United States",
        "Harbour.Space": "Barcelona, Spain",
        "Happy Even After": "New York City, United States",
        "Haque Law": "Birmingham, United States",
        "High Rise Financial": "Los Angeles, United States",
        "IvyPanda": "Central, Hong Kong",
        "International Society of Women Airline Pilots": "Las Vegas, United States",
        "International Sustainability Academy (ISA)": "Hamburg, Germany",
        "IHE Delft Institute for Water Education": "Delft, Netherlands",
        "Justin Magnuson Justice Reform Foundation": "Dallas, United States",
        "JCMM": "Brno, Czech Republic",
        "JFUNU": "Tokyo, Japan",
        "Kingston University": "London, United Kingdom",
        "Kühne Logistics University (KLU)": "Hamburg, Germany",
        "Kreditkortlistan": "Stockholm, Sweden",
        "Kevin McManus Law": "Kansas City, United States",
        "Law Office of Jae Lee": "Fort Lee, United States",
        "Law Offices of James A. Welcome": "Waterbury, United States",
        "Livinfrance": "Lille, France",
        "Loughborough University": "Loughborough, United Kingdom",
        "Lancaster University": "Lancaster, United Kingdom",
        "Marc Whitehead & Associates": "Houston, United States",
        "Meyer & Bowden, PLLC": "Fredericksburg, United States",
        "Meyer Wilson Werning": "Columbus, United States",
        "Med School Insiders": "Las Vegas, United States",
        "Malaysian Government": "Kuala Lumpur, Malaysia",
        "MyUS": "Sarasota, United States",
        "MBA Insight LLC": "New York City, United States",
        "NextLevel Student Scholarship": "New York City, United States",
        "NextLaw PLLC": "Ottawa, Canada",
        "Niara": "London, United Kingdom",
        "National University of Singapore": "Singapore, Singapore",
        "Nanyang Technological University": "Singapore, Singapore",
        "Nora's Nursery": "Katy, United States",
        "NYC Injury Attorneys P.C.": "New York City, United States",
        "Omni Law P.C.": "Los Angeles, United States",
        "OeAD, Austria": "Vienna, Austria",
        "OVC Scholarship Network": "California, United States",
        "Pinsky Law": "Ottawa, Canada",
        "PlagiarismSearch": "London, United Kingdom",
        "Puget Law Group": "Tacoma, United States",
        "Philadelphia Injury Lawyers, P.C.": "Philadelphia, United States",
        "Pittsburgh Injury Lawyers": "Pittsburgh, United States",
        "Pro-Care Medical Centers": "Austin, United States",
        "Quantic School of Business and Technology": "Washington, D.C., United States",
        "Queen Mary University of London": "London, United Kingdom",
        "Queen's University Belfast": "Belfast, United Kingdom",
        "Reel Fathers Rights": "Riverside, United States",
        "Robert Wilkos": "Georgia, United States",
        "Rapid Formations": "London, United Kingdom",
        "Royal Holloway University of London": "Egham, United Kingdom",
        "Royal College of Art": "London, United Kingdom",
        "Salvado Law": "Gwinnett, United States",
        "ServiceScape": "Wilmington, United States",
        "Shield Your Body": "Las Vegas, United States",
        "SBW Berlin": "Berlin, Germany",
        "Society of Women Engineers": "Chicago, United States",
        "Sprak Design": "Ahmedabad, India",
        "Storm Law Partners": "Illinois, United States",
        "Spencer & Associates": "Wood Hills, United States",
        "Shook & Stone": "Las Vegas, United States",
        "Support Creativity": "New York City, United States",
        "Simmons and Fletcher": "Houston, United States",
        "Sheffield Hallam University": "Sheffield, United Kingdom",
        "SOAS University of London": "London, United Kingdom",
        "SETC": "Atlanta, United States",
        "The Foray Hurst Firm": "Dallas, United States",
        "The Law Offices of J. Price McNamara": "Baton Rouge, United States",
        "The Malaysian Australian Alumni Council": "Kuala Lumpur, Malaysia",
        "The Smooth Movers": "Perth, Australia",
        "Teague Law": "Ellijay, United States",
        "The University of Lancashire": "Preston, United Kingdom",
        "The University of Sydney": "Sydney, Australia",
        "The University of Edinburgh": "Edinburgh, United Kingdom",
        "The University of Toledo": "Toledo, United States",
        "University College Cork": "Cork, Ireland",
        "University College Dublin": "Dublin, Ireland",
        "University of Southampton": "Southampton, United Kingdom",
        "University of Hull": "Hull, United Kingdom",
        "University of Bath": "Bath, United Kingdom",
        "University of Vaasa": "Vaasa, Finland",
        "University of Hertfordshire": "Hatfield, United Kingdom",
        "University of Birmingham": "Birmingham, United Kingdom",
        "University of Canterbury": "Christchurch, New Zealand",
        "University of Leeds": "Leeds, United Kingdom",
        "University of Sussex": "Brighton, United Kingdom",
        "University of Stirling": "Stirling, United Kingdom",
        "University of East London": "London, United Kingdom",
        "University of Reading": "Reading, United Kingdom",
        "University of Portsmouth": "Portsmouth, United Kingdom",
        "University of West London": "London, United Kingdom",
        "University of Wolverhampton": "Wolverhampton, United Kingdom",
        "University of Algarve": "Faro, Portugal",
        "University of Cyprus": "Nicosia, Cyprus",
        "University of Essex": "Colchester, United Kingdom",
        "University of Greenwich": "London, United Kingdom",
        "University of Bradford": "Bradford, United Kingdom",
        "University of St Andrews": "St Andrews, United Kingdom",
        "University of Tulsa": "Tulsa, United States",
        "University of Tasmania": "Hobart, Australia",
        "University of Technology Sydney (UTS)": "Sydney, Australia",
        "UNW Canberra": "Canberra, Australia",
        "UWE Bristol": "Bristol, United Kingdom",
        "UCL": "London, United Kingdom",
        "Valar Institute": "Washington, D.C., United States",
        "Vasquez Law Firm": "Raleigh, United States",
        "Vytautas Magnus University": "Kaunas, Lithuania",
        "VisaEnvoy": "Melbourne, Australia",
        "Wageningen University and Research": "Wageningen, Netherlands",
        "Wolfgang Pauli Institute": "Vienna, Austria",
        "Zaragoza Logistics Center (ZLC)": "Zaragoza, Spain",
        "Zide Law Group, LLC": "Glen Burnie, United States",

        "University of Queensland": "Brisbane, Australia",
        "Monash University": "Melbourne, Australia",
        "University of Sydney": "Sydney, Australia",
        "Australian National University": "Canberra, Australia",
        "University of Melbourne": "Melbourne, Australia",
        "University of New South Wales": "Sydney, Australia",
        "University of Adelaide": "Adelaide, Australia",
        "University of Western Australia": "Perth, Australia",
        "Queensland University of Technology": "Brisbane, Australia",
        "Curtin University": "Perth, Australia",
        "Macquarie University": "Sydney, Australia",
        "RMIT University": "Melbourne, Australia",
        "Deakin University": "Melbourne, Australia",
        "University of Technology Sydney": "Sydney, Australia",
        "University of Wollongong": "Wollongong, Australia",
        "University of Newcastle": "Newcastle, Australia",
        "Griffith University": "Gold Coast, Australia",
        "La Trobe University": "Melbourne, Australia",
        "Swinburne University of Technology": "Melbourne, Australia",
        "University of Tasmania": "Hobart, Australia",
        "Flinders University": "Adelaide, Australia",
        "James Cook University": "Townsville, Australia",
        "University of Canberra": "Canberra, Australia",
        "Bond University": "Gold Coast, Australia",
        "Charles Darwin University": "Darwin, Australia",
        "Western Sydney University": "Sydney, Australia",
       
        "University of Oxford": "Oxford, United Kingdom",
        "University of Cambridge": "Cambridge, United Kingdom",
        "University of Manchester": "Manchester, United Kingdom",
        "The University of Manchester": "Manchester, United Kingdom",
        "University of Edinburgh": "Edinburgh, United Kingdom",
        "The University of Edinburgh": "Edinburgh, United Kingdom",
        "University of Warwick": "Coventry, United Kingdom",
        "University College London": "London, United Kingdom",
        "Imperial College London": "London, United Kingdom",
        "King's College London": "London, United Kingdom",
        "London School of Economics and Political Science": "London, United Kingdom",
        "University of Bristol": "Bristol, United Kingdom",
        "University of Glasgow": "Glasgow, United Kingdom",
        "University of Birmingham": "Birmingham, United Kingdom",
        "University of Southampton": "Southampton, United Kingdom",
        "University of Leeds": "Leeds, United Kingdom",
        "University of Sheffield": "Sheffield, United Kingdom",
        "University of Nottingham": "Nottingham, United Kingdom",
        "Nottingham Trent University": "Nottingham, United Kingdom",
        "Queen Mary University of London": "London, United Kingdom",
        "Newcastle University": "Newcastle, United Kingdom",
        "University of Liverpool": "Liverpool, United Kingdom",
        "Cardiff University": "Cardiff, United Kingdom",
        "University of Exeter": "Exeter, United Kingdom",
        "University of York": "York, United Kingdom",
        "University of Bath": "Bath, United Kingdom",
        "Durham University": "Durham, United Kingdom",
        "University of Reading": "Reading, United Kingdom",
        "University of Sussex": "Brighton, United Kingdom",
        "Loughborough University": "Loughborough, United Kingdom",
        "University of Leicester": "Leicester, United Kingdom",
        "University of Surrey": "Guildford, United Kingdom",
        "University of Strathclyde": "Glasgow, United Kingdom",
        "University of Dundee": "Dundee, United Kingdom",
        "City University of London": "London, United Kingdom",
        "Brunel University of London": "London, United Kingdom",
        "Birkbeck, University of London": "London, United Kingdom",
        "Royal Holloway University of London": "London, United Kingdom",
        "University of East Anglia": "Norwich, United Kingdom",
        "University of Kent": "Canterbury, United Kingdom",
        "University of Essex": "Colchester, United Kingdom",
        "Oxford Brookes University": "Oxford, United Kingdom",
        "Aston University": "Birmingham, United Kingdom",
        "Heriot-Watt University": "Edinburgh, United Kingdom",
        "Middlesex University": "London, United Kingdom",
        "Manchester Metropolitan University": "Manchester, United Kingdom",
        "Northumbria University": "Newcastle, United Kingdom",
        "University of Hertfordshire": "Hatfield, United Kingdom",
        "University of Bedfordshire": "Luton, United Kingdom",
        "Arden University": "Online / Coventry, UK",
        "Arden University Online": "Online / Coventry, UK",

        "Harvard University": "Cambridge, United States",
        "Stanford University": "Stanford, United States",
        "Massachusetts Institute of Technology": "Cambridge, United States",
        "Yale University": "New Haven, United States",
        "Princeton University": "Princeton, United States",
        "Columbia University": "New York City, United States",
        "University of Pennsylvania": "Philadelphia, United States",
        "University of Chicago": "Chicago, United States",
        "University of California, Berkeley": "Berkeley, United States",
        "University of California, Los Angeles": "Los Angeles, United States",
        "University of California, San Diego": "San Diego, United States",
        "University of California, Davis": "Davis, United States",
        "Cornell University": "Ithaca, United States",
        "New York University": "New York City, United States",
        "Johns Hopkins University": "Baltimore, United States",
        "Northwestern University": "Evanston, United States",
        "University of Michigan": "Ann Arbor, United States",
        "Duke University": "Durham, United States",
        "Temple University": "Philadelphia, United States",
        "University of Southern California": "Los Angeles, United States",
        "Boston University": "Boston, United States",
        "Georgetown University": "Washington, D.C., United States",
        "American University Washington DC": "Washington, D.C., United States",
        "George Washington University": "Washington, D.C., United States",
        "University of Texas at Austin": "Austin, United States",
        "Georgia Institute of Technology": "Atlanta, United States",
        "Purdue University": "West Lafayette, United States",
        "University of Washington": "Seattle, United States",
        "University of Illinois Urbana-Champaign": "Urbana, United States",
        "University of North Carolina at Chapel Hill": "Chapel Hill, United States",
        "Michigan State University": "East Lansing, United States",
        "Ohio State University": "Columbus, United States",
        "Pennsylvania State University": "State College, United States",
        "University of Minnesota": "Minneapolis, United States",
        "Arizona State University": "Phoenix, United States",
        "University of Arizona": "Tucson, United States",
        "Northeastern University": "Boston, United States",
 
        "University of Toronto": "Toronto, Canada",
        "University of British Columbia": "Vancouver, Canada",
        "McGill University": "Montreal, Canada",
        "University of Alberta": "Edmonton, Canada",
        "McMaster University": "Hamilton, Canada",
        "University of Waterloo": "Waterloo, Canada",
        "University of Calgary": "Calgary, Canada",
        "University of Ottawa": "Ottawa, Canada",
        "Queen's University": "Kingston, Canada",
        "Dalhousie University": "Halifax, Canada",
        "Simon Fraser University": "Burnaby, Canada",
        "University of Victoria": "Victoria, Canada",
        "York University": "Toronto, Canada",
        "University of Guelph": "Guelph, Canada",
        "University of Saskatchewan": "Saskatoon, Canada",
        "Carleton University": "Ottawa, Canada",
        # EUROPE & IRELAND
        "University College Dublin": "Dublin, Ireland",
        "Trinity College Dublin": "Dublin, Ireland",
        "University of Galway": "Galway, Ireland",
        "University College Cork": "Cork, Ireland",
        "Dublin City University": "Dublin, Ireland",
        "University of Amsterdam": "Amsterdam, Netherlands",
        "Delft University of Technology": "Delft, Netherlands",
        "Utrecht University": "Utrecht, Netherlands",
        "Leiden University": "Leiden, Netherlands",
        "Wageningen University and Research": "Wageningen, Netherlands",
        "University of Groningen": "Groningen, Netherlands",
        "Erasmus University Rotterdam": "Rotterdam, Netherlands",
        "Maastricht University": "Maastricht, Netherlands",
        "Radboud University": "Nijmegen, Netherlands",
        "Lund University": "Lund, Sweden",
        "KTH Royal Institute of Technology": "Stockholm, Sweden",
        "Uppsala University": "Uppsala, Sweden",
        "Stockholm University": "Stockholm, Sweden",
        "University of Gothenburg": "Gothenburg, Sweden",
        "Umea University": "Umeå, Sweden",
        "University of Helsinki": "Helsinki, Finland",
        "Aalto University": "Helsinki, Finland",
        "University of Oslo": "Oslo, Norway",
        "University of Copenhagen": "Copenhagen, Denmark",
        "Aarhus University": "Aarhus, Denmark",
        "ETH Zurich": "Zurich, Switzerland",
        "University of Zurich": "Zurich, Switzerland",
        "Technical University of Munich": "Munich, Germany",
        "LMU Munich": "Munich, Germany",
        "Heidelberg University": "Heidelberg, Germany",
        "RWTH Aachen University": "Aachen, Germany",
        "ESMT Berlin": "Berlin, Germany",
        "University of Milan": "Milan, Italy",
        "University of Bologna": "Bologna, Italy",
        "Sapienza University of Rome": "Rome, Italy",
        "University of Barcelona": "Barcelona, Spain",
        
        "National University of Singapore": "Singapore",
        "Nanyang Technological University": "Singapore",
        "University of Hong Kong": "Hong Kong",
        "Tsinghua University": "Beijing, China",
        "Peking University": "Beijing, China",
        "Seoul National University": "Seoul, South Korea",
        "KAIST": "Daejeon, South Korea",
        "University of Tokyo": "Tokyo, Japan",
        "Kyoto University": "Kyoto, Japan",
  
        "Mundus MAPP": "Global (Consortium)",
        "GyanDhan": "New Delhi, India",
        "Quantic School of Business and Technology": "Washington, D.C., United States",
        "Valar Institute": "Washington, D.C., United States",
        "British Council": "Global / UK",
        "ACU (The Association of Commonwealth Universities)": "Commonwealth (Global)",
        "MPOWER Financing": "Washington, D.C., United States"
    }

    # --- PROCESSING LOGIC ---
    with docx2python(file_name) as doc_content:
        full_text = doc_content.text.replace('\\t', '')
        raw_lines = [line.strip() for line in full_text.split('\n') if line.strip()]

    all_scholarships = []
    current_block = []

    for line in raw_lines:
        if "Independent provider" in line or "Provided by university" in line:
            if current_block: all_scholarships.append(current_block)
            current_block = [line]
        else:
            if current_block is not None: current_block.append(line)
    if current_block: all_scholarships.append(current_block)

    final_data = []

    for block in all_scholarships:
        item = {
            "UNIVERSITY NAME": "Not specified",
            "SCHOLARSHIP NAME": "Not specified",
            "AMOUNT": "Not specified",
            "DEADLINE": "Not specified",
            "LOCATION": "Not specified",
            "OFFICIAL_SEARCH": "#"
        }

        for i in range(len(block)):
            val = block[i]
            if "Read more about eligibility" in val:
                if i + 1 < len(block): item["UNIVERSITY NAME"] = block[i+1]
                if i + 2 < len(block): item["LOCATION"] = block[i+2]
            if any(curr in val for curr in ["INR", "USD", "GBP", "EUR", "benefits"]):
                item["AMOUNT"] = val
            if val.lower() == "deadline" and i + 1 < len(block):
                item["DEADLINE"] = block[i+1]
            if val.lower() == "deadline" and i + 2 < len(block):
                name = block[i+2]
                if "based" not in name.lower() and "grant" not in name.lower():
                    item["SCHOLARSHIP NAME"] = name

        # --- SMART LOCATION FILLING ---
        clean_uni = item["UNIVERSITY NAME"].strip()
        # If document says "Unknown" or "Not available", use Knowledge Base
        if any(bad in item["LOCATION"] for bad in ["Not specified", "available", "Unknown", ""]):
            if clean_uni in uni_map:
                item["LOCATION"] = uni_map[clean_uni]
        
        # Final cleanup for consistency
        if any(bad in item["LOCATION"] for bad in ["Not specified", "available", "Unknown"]):
            item["LOCATION"] = "Not specified"

        # --- OFFICIAL SEARCH LINK ---
        search_query = f"{item['SCHOLARSHIP NAME']} {item['UNIVERSITY NAME']} official website".replace(" ", "+")
        item["OFFICIAL_SEARCH"] = f"https://www.google.com/search?q={search_query}"

        if item["UNIVERSITY NAME"] != "Not specified":
            final_data.append(item)

    with open('FINAL_MASTER_DATA.json', 'w', encoding='utf-8') as f:
        json.dump(final_data, f, indent=4, ensure_ascii=False)

    print(f"SUCCESS! {len(final_data)} scholarships processed into FINAL_MASTER_DATA.json")

# RUN
process_master_scholarships('data.docx')